swagger: "2.0"
info:
  description: "API de Itens"
  version: "1.0.0"
  title: "API de Itens"
host: "localhost:5000"
basePath: "/"
tags:
  - name: "item"
    description: "Operações sobre itens"
schemes:
  - "http"
paths:
  /item:
    get:
      tags:
        - "item"
      summary: "Obter todos os itens"
      responses:
        200:
          description: "Lista de itens"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Item"
    post:
      tags:
        - "item"
      summary: "Criar um novo item"
      parameters:
        - in: "body"
          name: "body"
          description: "Item a ser criado"
          required: true
          schema:
            $ref: "#/definitions/Item"
      responses:
        201:
          description: "Item criado"
          schema:
            $ref: "#/definitions/Item"
  /item/{itemId}:
    put:
      tags:
        - "item"
      summary: "Atualizar um item existente"
      parameters:
        - name: "itemId"
          in: "path"
          required: true
          type: "integer"
        - in: "body"
          name: "body"
          description: "Dados do item a serem atualizados"
          required: true
          schema:
            $ref: "#/definitions/Item"
      responses:
        200:
          description: "Item atualizado"
          schema:
            $ref: "#/definitions/Item"
        404:
          description: "Item não encontrado"
    delete:
      tags:
        - "item"
      summary: "Deletar um item existente"
      parameters:
        - name: "itemId"
          in: "path"
          required: true
          type: "integer"
      responses:
        204:
          description: "Item deletado"
        404:
          description: "Item não encontrado"
definitions:
  Item:
    type: "object"
    required:
      - "id"
      - "name"
      - "description"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      description:
        type: "string"